muxRecords: true
rtpJitterBuffer: 
  latency: "140"
  retransmission: "false"
opus:
  rtp:
    caps: application/x-rtp,payload=111,encoding-name=OPUS 
    pay: rtpopuspay
    depay: >-
      rtpopusdepay !
      opusparse 
  decode: "decodebin"
  encode:
    fx: >-
      opusenc name=audio_encoder_fx audio-type=2048 bitrate-type=1 perfect-timestamp=true !
      opusparse
vp8:
  rtp:
    caps: application/x-rtp,encoding-name=VP8-DRAFT-IETF-01
    pay: rtpvp8pay
    depay: rtpvp8depay
  decode: "vp8dec"
  encode:
    raw: >-
      vp8enc name=video_encoder_in deadline=1 cpu-used=4 end-usage=1
      undershoot=95 keyframe-max-dist=999999 max-quantizer=56 qos=true
    fx: >-
      vp8enc name=video_encoder_fx deadline=1 cpu-used=4 end-usage=1
      undershoot=95 keyframe-max-dist=999999 max-quantizer=56 qos=true
x264:
  rtp:
    caps: application/x-rtp,encoding-name=H264 
    pay: rtph264pay config-interval=-1
    depay: >-
      rtph264depay !
      h264parse 
  decode: avdec_h264
  encode:
    raw: >-
      x264enc name=video_encoder_raw pass=17 multipass-cache-file=data/{{.Namespace}}/logs/{{.FilePrefix}}.x264_pass.raw.log 
      speed-preset=ultrafast tune=zerolatency qos=true !
      h264parse !
      video/x-h264, profile=high
    fx: >-
      x264enc name=video_encoder_fx pass=17 multipass-cache-file=data/{{.Namespace}}/logs/{{.FilePrefix}}.x264_pass.fx.log 
      speed-preset=ultrafast tune=zerolatency qos=true !
      video/x-h264, profile=high !
      h264parse 
nv264:
  rtp:
    caps: application/x-rtp,encoding-name=H264 
    pay: rtph264pay config-interval=-1
    depay: >-
      rtph264depay !
      h264parse 
  decode: avdec_h264
  encode:
    raw: >-
      nvh264enc name=video_encoder_raw rc-mode=3 preset=3 gop-size=15 bframes=4 rc-lookahead=20 zerolatency=true qos=true !
      video/x-h264, profile=high !
      h264parse
    fx: >-
      nvh264enc name=video_encoder_fx rc-mode=3 preset=3 gop-size=15 bframes=4 rc-lookahead=20 zerolatency=true qos=true !
      video/x-h264, profile=high !
      h264parse