commonAudioRTPJitterBuffer: rtpjitterbuffer name=audio_buffer latency=140 do-retransmission=false
commonVideoRTPJitterBuffer: rtpjitterbuffer name=video_buffer latency=140 do-retransmission=false
commonAudioRawCaps: >-
    audioconvert ! 
    audio/x-raw,channels=1
commonVideoRawCaps: >-
    videoconvert ! 
    videorate ! 
    videoscale ! 
    video/x-raw{{.FrameRate}}{{.Width}}{{.Height}}, format=I420, colorimetry=bt601, chroma-site=jpeg, pixel-aspect-ratio=1/1 
commonVideoRawCapsLight: >-
    videoconvert ! 
    video/x-raw, format=I420, colorimetry=bt601, chroma-site=jpeg
opus:
  rtp:
    caps: application/x-rtp,payload=111,encoding-name=OPUS 
    pay: rtpopuspay
    depay: >-
      rtpopusdepay !
      opusparse 
  decode: decodebin
  encode: >-
    opusenc name={{.Name}} audio-type=2048 bitrate-type=1 perfect-timestamp=true !
    opusparse
vp8:
  rtp:
    caps: application/x-rtp,encoding-name=VP8-DRAFT-IETF-01
    pay: rtpvp8pay
    depay: rtpvp8depay
  decode: vp8dec
  encode: >-
    vp8enc name={{.Name}} deadline=1 cpu-used=4 end-usage=1
    undershoot=95 keyframe-max-dist=999999 max-quantizer=56 qos=true
x264:
  rtp:
    caps: application/x-rtp,encoding-name=H264 
    pay: rtph264pay config-interval=-1
    depay: >-
      rtph264depay !
      h264parse 
  decode: avdec_h264
  encode: >-
    x264enc name={{.Name}} pass=17 multipass-cache-file=data/{{.Namespace}}/logs/{{.FilePrefix}}.x264_pass.{{.Name}}.log 
    speed-preset=ultrafast tune=zerolatency qos=true !
    video/x-h264, profile=high ! 
    h264parse
nv264:
  rtp:
    caps: application/x-rtp,encoding-name=H264 
    pay: rtph264pay config-interval=-1
    depay: >-
      rtph264depay !
      h264parse 
  decode: avdec_h264
  encode: >-
    nvh264enc name={{.Name}} rc-mode=3 preset=3 gop-size=15 bframes=4 rc-lookahead=10 i-adapt=true zerolatency=true qos=true !
    video/x-h264, profile=high !
    h264parse