forceEncodingSize: false
rtpJitterBuffer: 
  latency: "140"
  retransmission: "false"
vp8:
  decode: "vp8dec"
  encode:
    fast: >-
      vp8enc name=encoder deadline=1 cpu-used=4 end-usage=1 target-bitrate=500000 
      undershoot=95 keyframe-max-dist=999999 max-quantizer=56 qos=true
    relaxed: >-
      vp8enc deadline=1 cpu-used=4 end-usage=1 target-bitrate=800000 
      undershoot=95 keyframe-max-dist=999999 max-quantizer=56
x264:
  decode: "avdec_h264"
  encode:
    fast: >-
      x264enc name=encoder pass=17 multipass-cache-file=data/${namespace}/logs/${prefix}.x264_pass.log 
      speed-preset=ultrafast tune=zerolatency qos=true !
      video/x-h264, profile=high
    relaxed: >-
      x264enc pass=17 multipass-cache-file=data/${namespace}/logs/${prefix}.x264_pass.relaxed.log 
      speed-preset=ultrafast !
      video/x-h264, profile=high
nv264:
  decode: "nvh264dec"
  encode:
    fast: >-
      nvh264enc name=encoder rc-mode=3 preset=4 gop-size=15 zerolatency=true qos=true !
      video/x-h264, profile=high
    relaxed: >-
      nvh264enc rc-mode=3 preset=4 gop-size=15 !
      video/x-h264, profile=high
opus:
  decode: "decodebin"
  encode:
    fast: "opusenc name=encoder audio-type=2048 bitrate-type=1 perfect-timestamp=true"
    relaxed: "opusenc audio-type=2048 bitrate-type=1"